import { Location, Employee } from './types';

export const EMPLOYEES: Employee[] = [
  { id: "7904", name: "胡淑惠" },
  { id: "10801", name: "Porter" },
  { id: "8207", name: "許振明" },
  { id: "9023", name: "胡文振" },
  { id: "9017", name: "邱增榕" },
  { id: "10608", name: "郭汝瀅" },
  { id: "11401", name: "蕭瑄萱" },
  { id: "10904", name: "廖姿玲" },
  { id: "11415", name: "許光志" },
  { id: "11404", name: "林佳賢" },
  { id: "11029", name: "許國輝" },
  { id: "11020", name: "陳瑩盈" },
  { id: "11215", name: "郭宜穎" },
  { id: "9803", name: "林家汝" },
  { id: "9907", name: "曾薪桉" },
  { id: "10103", name: "高銘澤" },
  { id: "10811", name: "盧佑昇" },
  { id: "10921", name: "林聖凱" },
  { id: "11214", name: "許淇幃" },
  { id: "11405", name: "楊富翔" },
  { id: "9916", name: "林昆弘" },
  { id: "10401", name: "蘇俊吉" },
  { id: "10513", name: "卓煜盛" },
  { id: "11207", name: "賴麒卉" },
  { id: "11210", name: "王俊閔" },
  { id: "11218", name: "印詠" },
  { id: "11303", name: "顏註文" },
  { id: "11410", name: "張博智" },
  { id: "11411", name: "王鍇迅" },
  { id: "11111", name: "鐘銘賢" },
  { id: "11402", name: "許明燕" },
  { id: "10916", name: "白泓諭" },
  { id: "10114", name: "詹嘉寶" },
  { id: "10813", name: "葉治廷" },
  { id: "11018", name: "周秉鴻" },
  { id: "11023", name: "吳承諺" },
  { id: "11413", name: "劉聖佑" },
  { id: "9707", name: "徐世勇" },
  { id: "9904", name: "鐘珮心" },
  { id: "9918", name: "林文隆" },
  { id: "11203", name: "薛瑞文" },
  { id: "8612", name: "陳俊宇" },
  { id: "10920", name: "汪猜" },
  { id: "11105", name: "林義軒" },
  { id: "11113", name: "蕭豐斌" },
  { id: "11204", name: "猜內" },
  { id: "8808", name: "蕭永裕" },
  { id: "10805", name: "鄭宇勝" },
  { id: "10902", name: "楊昇興" },
  { id: "11116", name: "顏家文" },
  { id: "11219", name: "蘇挺" },
  { id: "11407", name: "他那功" },
  { id: "11408", name: "東答康" },
  { id: "11409", name: "楊錫琮" },
  { id: "11416", name: "陳子敬" },
  { id: "10504", name: "鐘文謙" },
  { id: "10709", name: "董鎧稻" },
  { id: "11015", name: "馬哪" },
  { id: "11114", name: "羅濟宏" },
  { id: "11216", name: "吳替才" },
  { id: "11103", name: "陳俞儒" },
  { id: "10912", name: "賴佳瑜" },
  { id: "11110", name: "尤亭惟" },
  { id: "11208", name: "陳冠閔" },
  { id: "11304", name: "王玫娟" },
  { id: "11201", name: "王偉全" },
  { id: "11209", name: "賴敬鵬" },
  { id: "8807", name: "梁瑞雱" },
  { id: "10823", name: "蕭允嶺" },
  { id: "11125", name: "董光展" }
];

export const PREDEFINED_LOCATIONS: Location[] = [
  { region: "台北", name: "內湖區金湖路365號", hours: 2.5 },
  { region: "新北", name: "淡水區崁頂里", hours: 3.0 },
  { region: "新竹", name: "湖口542營區 (湖口北測中心)", hours: 1.5 },
  { region: "新竹", name: "新竹市北區東大路三段179巷", hours: 1.5 },
  { region: "新竹", name: "新竹關西新訓中心 (老庚寮22號)", hours: 2.0 },
  { region: "新竹", name: "新竹空軍基地", hours: 1.5 },
  { region: "新竹", name: "工研院", hours: 1.5 },
  { region: "桃園", name: "桃園市中壢區龍東路1號", hours: 2.0 },
  { region: "桃園", name: "銀河營區 (龜山區樹人路305巷296號)", hours: 2.0 },
  { region: "桃園", name: "高山頂營區 (雄獅部隊)", hours: 2.0 },
  { region: "桃園", name: "彗星營區", hours: 2.0 },
  { region: "桃園", name: "桃園高鐵站", hours: 2.0 },
  { region: "桃園", name: "桃科5號門", hours: 2.0 },
  { region: "桃園", name: "台灣大電力 (桃園觀音)", hours: 2.0 },
  { region: "桃園", name: "臺威 (桃園龜山)", hours: 2.0 },
  { region: "桃園", name: "桃園金龍營區", hours: 2.0 },
  { region: "桃園", name: "桃園市楊梅區楊湖路一段367巷", hours: 2.0 },
  { region: "宜蘭", name: "宜蘭紅柴林", hours: 3.5 },
  { region: "宜蘭", name: "宜蘭武荖坑", hours: 3.0 },
  { region: "宜蘭", name: "龍德造船廠第六廠", hours: 3.0 },
  { region: "宜蘭", name: "宜蘭蘇澳乾塢營區", hours: 3.0 },
  { region: "宜蘭", name: "宜蘭蘇澳港", hours: 3.0 },
  { region: "高雄", name: "海軍左營基地 (左營區介壽路10號)", hours: 2.0 },
  { region: "高雄", name: "左營中正哨", hours: 2.0 },
  { region: "高雄", name: "高雄陸戰隊隊史館", hours: 2.0 },
  { region: "高雄", name: "金湯營區 (高雄步校)", hours: 2.0 },
  { region: "高雄", name: "高雄天山營區", hours: 1.5 },
  { region: "高雄", name: "高雄市旗津區中洲二路462-6號 (精一)", hours: 2.0 },
  { region: "高雄", name: "嘉興營區", hours: 1.5 },
  { region: "屏東", name: "屏東空軍基地", hours: 2.0 },
  { region: "屏東", name: "加祿堂營區", hours: 2.5 },
  { region: "屏東", name: "恆春鎮東海路", hours: 3.5 },
  { region: "台南", name: "台南陸軍航空特戰指揮部", hours: 1.5 },
  { region: "台南", name: "台南空軍基地", hours: 1.5 },
  { region: "台南", name: "台南長安營區 (仁德智測站)", hours: 1.5 },
  { region: "台南", name: "台南市仁德區保仁路195號", hours: 1.5 },
  { region: "花蓮", name: "七星潭 (經台東大學)", hours: 7.5 },
  { region: "台東", name: "志航空軍基地 (台東市志航路三段)", hours: 4.5 },
];

export const LOCATION_GROUPS = PREDEFINED_LOCATIONS.reduce((groups, loc) => {
  if (!groups[loc.region]) groups[loc.region] = [];
  groups[loc.region].push(loc);
  return groups;
}, {} as Record<string, Location[]>);